### ISSUE TITLE
既存電子データについて

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [soja-suidou/web_gis#1]
@nagasawajun 
\\soja\総社市\水道施設WEB閲覧システム導入業務\オリジナルデータ
にデータを置いておきました。
ご確認ください。
本件は，村田に引継ぎの予定です。

**Comment by yamamoto-ryuzo** [comment]
@nagasawajun
データ確認の上，再度仕様書を作成願います。
結構，高額になると思うので，取捨選択して発注かもしれませんが，全体をとりあず把握したいので。
仕様書は適当に
\\soja\総社市\水道施設WEB閲覧システム導入業務\
内に置いてくれてもOKです。

**Comment by nagasawajun** [comment]
承知いたしました。仕様書を保存したら再度ご連絡いたします。

**Comment by nagasawajun** [comment]
いただいたデータの事も追記し、以下の場所に仕様書を保存しました。
\\soja\総社市\水道施設WEB閲覧システム導入業務
総社市水道施設WEB閲覧システム構築 仕様書.docx

旧総社市配管図が思いのほかボリュームが多かったので、作業日数を10→20日に増やしております。

ご確認お願いいたします。
